twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        describe: '%describe%'
        keywords: '%keywords%'
        contact: '%contact%'
        cel: '%cel%'
        info: '%info%'
        facebook: '%facebook%'
