vich_uploader:
    db_driver: orm
    mappings:
        solution_image:
            uri_prefix: /images/solution
            upload_destination: '%kernel.project_dir%/public/images/solution'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
        post_image:
            uri_prefix: /images/post
            upload_destination: '%kernel.project_dir%/public/images/post'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid
        formation_image:
            uri_prefix: /images/formation
            upload_destination: '%kernel.project_dir%/public/images/formation'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: vich_uploader.namer_uniqid